### ISSUE TITLE
qconf可以使用在docker集群中么

### ISSUE THREAD

**Issue by pyloque** [Qihoo360/QConf#21]
qconf的共享内存是否可以跨越容器边界？

**Comment by bigpyer** [comment]
qconf的共享内存就是ipc share mem，应该是不能跨容器的。

**Comment by demohi** [comment]
同问

**Comment by CatKang** [comment]
可以在docker中使用

需要保证agent和客户端接口可以访问到同一个共享内存和消息队列

**Comment by Misfit-John** [comment]
+10086希望至少可以有一个docker demo

**Comment by demohi** [comment]
可以使用，主要解决共享内存的问题

## 第一种方法
使用phusion/baseimage，下面dockerfile 我做了删减，大家可以看[phusion/baseimage](https://github.com/phusion/baseimage-docker)
```
FROM phusion/baseimage:latest

RUN  apt-get update && apt-get install -y qconf\
 && rm -rf /var/lib/apt/lists/*

RUN ldconfig /usr/local/qconf/

RUN echo "kernel.shmmax = 2048000000" >> /etc/sysctl.conf
RUN echo "kernel.shmall = 4294967296" >> /etc/sysctl.conf
RUN mkdir -p /etc/my_init.d
COPY ./init.sh /etc/my_init.d/init.sh
RUN chmod +x /etc/my_init.d/init.sh
CMD ["/sbin/my_init"]

```
运行时，需要--privileged=true

## 第二种方法是

使用--ipc=host

参考[Docker里莫名其妙的/proc/sys/kernel/shmmax](http://weibo.com/p/1001603829422523342026)

**Comment by lzjohnny** [comment]
最近在Docker和K8S集群中使用qconf也同样遇到了这个问题，结论是Docker和K8S中均可用
1. Docker中使用即按照 @demohi 的方式，使用--ipc=host：
```
IPC with the Host
docker run --ipc=host <image>

IPC with another Container
docker run --ipc=container:<id> <image>
```
2. K8S/Kubernetes中使用 `hostIPC: true` 配置参数：

在Deployment yaml文件的 spec.template.spec 里、与containers、volumes同级的位置添加 hostIPC: true
qconf以及需要使用qconf的deployment文件均需要添加

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      hostIPC: true
      containers:
        - name: nginx
          image: xxx
          command: ["/usr/sbin/nginx"]
          args: ["-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qconf
spec:
  selector:
    matchLabels:
      app: qconf
  template:
    metadata:
      labels:
        app: qconf
    spec:
      hostIPC: true
      containers:
        - name: qconf
          image: xxx
          command: ["/bin/sh", "-c"]
          args: ["sh /usr/local/qconf/bin/agent-cmd.sh start; while true; do echo hello world; sleep 1; done"]
```
